name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up the Java JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B test
      
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: target/

    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: target/site/jacoco/jacoco.csv

    - name: setting environments variables
      env:
        GH_COVERAGE: ${{ steps.jacoco.outputs.coverage }}
        GH_BRANCH_COVERAGE: ${{ steps.jacoco.outputs.branches }}
      run: |
         echo "COVERAGE=$(echo $GH_COVERAGE*100)" >> $GITHUB_ENV
         echo "BRANCH_COVERAGE=$(echo $GH_BRANCH_COVERAGE*100)" >> $GITHUB_ENV
      
    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
        echo "HEDO [$COVERAGE]"
        echo "HEDO [$BRANCH_COVERAGE]"
        echo "HEDO-2 ${{ env.COVERAGE }}"
        echo "HEDO-2 ${{ env.BRANCH_COVERAGE }}"

    - uses: actions/github-script@v6
      with:
        script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '====>   $COVERAGE <br>\n $BRANCH_COVERAGE'
            })
            
    - uses: actions/github-script@v6
      with:
        script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## JaCoCo Test Coverage Summary <br>\n * __Coverage:__ ${{ steps.jacoco.outputs.coverage }}*100 <br>\n * __Branches:__ ${{ steps.jacoco.outputs.branches }}*100'
            })
            
    - name: checking out branch 'dev-1'
      uses: actions/checkout@v4
      with:
        ref: dev-1
    
    - name: Commit the badge (if it changed)
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --global user.name 'mehul-kaps'
          git config --global user.email 'mehul.kaps@icloud.com'
          git add -A
          git commit -m "Autogenerated JaCoCo coverage badge"
          git push
        fi

    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/