name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up the Java JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B test
      
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: target/

    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: target/site/jacoco/jacoco.csv

    - name: Set coverage environments variables
      env:
        GH_COVERAGE: ${{ steps.jacoco.outputs.coverage }}
        GH_BRANCH_COVERAGE: ${{ steps.jacoco.outputs.branches }}
        NUM: ${{ steps.jacoco.outputs.branches }}
      run: |
          echo "GITHUB_RUN_NUMBER_WITH_OFFSET=$(($NUM * 200))" >> $GITHUB_ENV
          echo "COVERAGE=$(echo $GH_COVERAGE*100 | bc)" >> $GITHUB_ENV
          echo "BRANCH_COVERAGE=$(echo $GH_BRANCH_COVERAGE*100 | bc)" >> $GITHUB_ENV
      
    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
        echo "HEDO-1 [$COVERAGE]"
        echo "HEDO-1 [$BRANCH_COVERAGE]"
        echo "HEDO-2 ${{ env.COVERAGE }}"
        echo "HEDO-2 ${{ env.BRANCH_COVERAGE }}"
           
    - name: Comment coverage statistics on Pull Requet(PR)        
      uses: actions/github-script@v6
      with:
        script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## JaCoCo Test Coverage Summary <br>\n * __Coverage:__ ${{ env.COVERAGE }} <br>\n * __Branches:__ ${{ env.BRANCH_COVERAGE }}'
            })
            
    - name: 'Check Coverate Minimum Thresold, FAIL the workflow if below Thresold'
      run: |
           echo "Success! ${{ env.GITHUB_RUN_NUMBER_WITH_OFFSET }}"
           echo "Success! ${{ env.COVERAGE }}"
           echo "Success! ${{ env.BRANCH_COVERAGE }}"
           if [[ $(echo "$COVERAGE <= 60.00" | bc -l) -eq 1 ]]; then
              echo "Coverage $COVERAGE is less than 80%, We must fail here."
              exit 1
           fi  

